### ISSUE TITLE
[5.0-beta] GenshinImpactHelper.exe -- бесконечный редирект 

### ISSUE THREAD

**Issue by thisVioletHydra** [satan007/genshin-impact-gacha-helper#1]
при тыкании в .exe постоянно редиректит на гитхаб как то так

**Comment by thisVioletHydra** [comment]
@satan007 че делать?

**Comment by satan007** [comment]
> @satan007 че делать?

Я глупый. Забыл поменять версию внутри приложения. Сорь торопился обновиться из за сломанной истории. Сейчас обновлю файлы.

**Comment by satan007** [comment]
> @satan007 че делать?

Обновил файлы. Проверьте всё ли работает.

**Comment by thisVioletHydra** [comment]
робит, пасиб
